pipeline:
  build: 
    image: registry.cn-hangzhou.aliyuncs.com/acs/maven
    commands:
      - mvn clean package -DskipTests
    volumes:
      - /root/maven/repository:/root/.m2/repository
      - /root/maven/settings.xml:/usr/share/maven/conf/settings.xml
  
  publish:
    image: docker
    secrets: [docker_username,docker_password]
    commands:
        - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com/pipipan/meetingroom
        - docker build -t registry.cn-shenzhen.aliyuncs.com/pipipan/backend:master -f Dockerfile .
        - docker push registry.cn-shenzhen.aliyuncs.com/pipipan/backend:master
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    when:
        branch: master
        status: success

  deploy:
    image: appleboy/drone-ssh
    host: 129.211.119.51
    secrets: [ssh_username, ssh_password]
    port: 22
    script:
      - /root/shell/backend-deployment.sh

